/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author javks
 */
public class telaCalculadora extends javax.swing.JFrame {

    /**
     * Creates new form telaCalculadora
     */
    public telaCalculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton6 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jTFNumeros = new javax.swing.JTextField();
        bT1 = new javax.swing.JButton();
        bT2 = new javax.swing.JButton();
        bT3 = new javax.swing.JButton();
        bT4 = new javax.swing.JButton();
        bT5 = new javax.swing.JButton();
        bT6 = new javax.swing.JButton();
        bT7 = new javax.swing.JButton();
        bT8 = new javax.swing.JButton();
        bT9 = new javax.swing.JButton();
        bT0 = new javax.swing.JButton();
        bTPonto = new javax.swing.JButton();
        bTMenos = new javax.swing.JButton();
        bTMais = new javax.swing.JButton();
        bTVezes = new javax.swing.JButton();
        bTDividir = new javax.swing.JButton();
        bTCalcular = new javax.swing.JButton();
        jTFHistorico = new javax.swing.JTextField();
        bTLimpar = new javax.swing.JButton();

        jButton6.setText("jButton1");

        jButton13.setText("jButton1");

        jButton17.setText("jButton1");

        jButton21.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTFNumeros.setEditable(false);
        jTFNumeros.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jTFNumeros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFNumerosActionPerformed(evt);
            }
        });

        bT1.setText("1");
        bT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bT1ActionPerformed(evt);
            }
        });

        bT2.setText("2");
        bT2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bT2ActionPerformed(evt);
            }
        });

        bT3.setText("3");
        bT3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bT3ActionPerformed(evt);
            }
        });

        bT4.setText("4");
        bT4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bT4ActionPerformed(evt);
            }
        });

        bT5.setText("5");
        bT5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bT5ActionPerformed(evt);
            }
        });

        bT6.setText("6");
        bT6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bT6ActionPerformed(evt);
            }
        });

        bT7.setText("7");
        bT7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bT7ActionPerformed(evt);
            }
        });

        bT8.setText("8");
        bT8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bT8ActionPerformed(evt);
            }
        });

        bT9.setText("9");
        bT9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bT9ActionPerformed(evt);
            }
        });

        bT0.setText("0");
        bT0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bT0ActionPerformed(evt);
            }
        });

        bTPonto.setText(".");
        bTPonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTPontoActionPerformed(evt);
            }
        });

        bTMenos.setText("-");
        bTMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTMenosActionPerformed(evt);
            }
        });

        bTMais.setText("+");
        bTMais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTMaisActionPerformed(evt);
            }
        });

        bTVezes.setText("*");

        bTDividir.setText("/");

        bTCalcular.setText("Calcular");
        bTCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTCalcularActionPerformed(evt);
            }
        });

        jTFHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFHistoricoActionPerformed(evt);
            }
        });

        bTLimpar.setText("Limpar");
        bTLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bTLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(bTMais, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(bTVezes, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(bTDividir, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(bT7, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(bT8, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(bT9, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(bT4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(bT5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(bT6, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(bT0, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(bTPonto, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(bTMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(bTCalcular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTFHistorico, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTFNumeros, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bT1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bT2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bT3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(19, 19, 19))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jTFHistorico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFNumeros, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bT1)
                    .addComponent(bT2)
                    .addComponent(bT3))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bT4)
                    .addComponent(bT5)
                    .addComponent(bT6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bT7)
                    .addComponent(bT8)
                    .addComponent(bT9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bT0)
                    .addComponent(bTPonto)
                    .addComponent(bTMenos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bTMais)
                    .addComponent(bTVezes)
                    .addComponent(bTDividir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bTCalcular)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bTLimpar)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFNumerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFNumerosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFNumerosActionPerformed

    private void bT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bT1ActionPerformed
        // TODO add your handling code here:
        jTFNumeros.setText(jTFNumeros.getText() + "1");
    }//GEN-LAST:event_bT1ActionPerformed

    private void jTFHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFHistoricoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFHistoricoActionPerformed
    double numero;
    String sinal;
    private void bTMaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTMaisActionPerformed
        // TODO add your handling code here:
        if (jTFHistorico.getText().length() == 0){
            numero = Double.parseDouble(jTFNumeros.getText());
            jTFHistorico.setText(jTFNumeros.getText() + "+");
            jTFNumeros.setText("");
        }else{
            numero = numero + Double.parseDouble(jTFNumeros.getText());
            jTFHistorico.setText(Double.toString(numero)+ "+");
            jTFNumeros.setText(null);
                    
        }
        
        
    }//GEN-LAST:event_bTMaisActionPerformed

    private void bTLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTLimparActionPerformed
        // TODO add your handling code here:
            jTFNumeros.setText("");
            jTFHistorico.setText("");
    }//GEN-LAST:event_bTLimparActionPerformed

    private void bTCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTCalcularActionPerformed
        // TODO add your handling code here:
        numero = numero + Double.parseDouble(jTFNumeros.getText());
            jTFHistorico.setText(Double.toString(numero)+ "+");
            jTFNumeros.setText(Double.toString(numero));
    }//GEN-LAST:event_bTCalcularActionPerformed

    private void bT2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bT2ActionPerformed
        // TODO add your handling code here:
        jTFNumeros.setText(jTFNumeros.getText() + "2");
    }//GEN-LAST:event_bT2ActionPerformed

    private void bT3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bT3ActionPerformed
        // TODO add your handling code here:
        jTFNumeros.setText(jTFNumeros.getText() + "3");
    }//GEN-LAST:event_bT3ActionPerformed

    private void bT4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bT4ActionPerformed
        // TODO add your handling code here:
        jTFNumeros.setText(jTFNumeros.getText() + "4");
    }//GEN-LAST:event_bT4ActionPerformed

    private void bT5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bT5ActionPerformed
        // TODO add your handling code here:
        jTFNumeros.setText(jTFNumeros.getText() + "5");
    }//GEN-LAST:event_bT5ActionPerformed

    private void bT6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bT6ActionPerformed
        // TODO add your handling code here:
        jTFNumeros.setText(jTFNumeros.getText() + "6");
    }//GEN-LAST:event_bT6ActionPerformed

    private void bT7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bT7ActionPerformed
        // TODO add your handling code here:
        jTFNumeros.setText(jTFNumeros.getText() + "7");
    }//GEN-LAST:event_bT7ActionPerformed

    private void bT8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bT8ActionPerformed
        // TODO add your handling code here:
        jTFNumeros.setText(jTFNumeros.getText() + "8");
    }//GEN-LAST:event_bT8ActionPerformed

    private void bT9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bT9ActionPerformed
        // TODO add your handling code here:
        jTFNumeros.setText(jTFNumeros.getText() + "9");
    }//GEN-LAST:event_bT9ActionPerformed

    private void bT0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bT0ActionPerformed
        // TODO add your handling code here:
        jTFNumeros.setText(jTFNumeros.getText() + "0");
    }//GEN-LAST:event_bT0ActionPerformed

    private void bTPontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTPontoActionPerformed
        // TODO add your handling code here:
        jTFNumeros.setText(jTFNumeros.getText() + ".");
    }//GEN-LAST:event_bTPontoActionPerformed

    private void bTMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTMenosActionPerformed
        // TODO add your handling code here:
        if (jTFHistorico.getText().length() == 0){
            numero = Double.parseDouble(jTFNumeros.getText());
            jTFHistorico.setText(jTFNumeros.getText() + "-");
            jTFNumeros.setText("");
        }else{
            numero = numero - Double.parseDouble(jTFNumeros.getText());
            jTFHistorico.setText(Double.toString(numero)+ "-");
            jTFNumeros.setText(null);
    }//GEN-LAST:event_bTMenosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaCalculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bT0;
    private javax.swing.JButton bT1;
    private javax.swing.JButton bT2;
    private javax.swing.JButton bT3;
    private javax.swing.JButton bT4;
    private javax.swing.JButton bT5;
    private javax.swing.JButton bT6;
    private javax.swing.JButton bT7;
    private javax.swing.JButton bT8;
    private javax.swing.JButton bT9;
    private javax.swing.JButton bTCalcular;
    private javax.swing.JButton bTDividir;
    private javax.swing.JButton bTLimpar;
    private javax.swing.JButton bTMais;
    private javax.swing.JButton bTMenos;
    private javax.swing.JButton bTPonto;
    private javax.swing.JButton bTVezes;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton6;
    private javax.swing.JTextField jTFHistorico;
    private javax.swing.JTextField jTFNumeros;
    // End of variables declaration//GEN-END:variables
}
